# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque-restriction}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Richard Huang"]
  s.date = %q{2011-04-03}
  s.description = %q{resque-restriction is an extension to resque queue system that restricts the execution number of certain jobs in a period time, the exceeded jobs will be executed at the next period.}
  s.email = %q{flyerhzm@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".rvmrc.example",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/resque-restriction.rb",
    "lib/resque-restriction/restriction_extensions.rb",
    "lib/resque-restriction/restriction_job.rb",
    "rails/init.rb",
    "resque-restriction.gemspec",
    "spec/redis-test.conf",
    "spec/resque-restriction/restriction_extensions_spec.rb",
    "spec/resque-restriction/restriction_job_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/flyerhzm/resque-restriction}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{resque-restriction is an extension to resque queue system that restricts the execution number of certain jobs in a period time.}
  s.test_files = [
    "spec/resque-restriction/restriction_extensions_spec.rb",
    "spec/resque-restriction/restriction_job_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<resque>, [">= 1.7.0"])
    else
      s.add_dependency(%q<resque>, [">= 1.7.0"])
    end
  else
    s.add_dependency(%q<resque>, [">= 1.7.0"])
  end
end

